language: cpp
compiler:
  - g++
before_install:
  -sudo apt-get update
  -sudo apt-get install libgtest-dev
script:
  - cd Analisis
  - mkdir build
  - cd helloworld
  - cmake cmake -H. -B../build
  - cd ../build
  - make
  - ./hello
  - ls
  - ls

  
