language: cpp

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgtest-dev
  - sudo apt-get install -y cmake
  - ls
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
compiler:
  - g++

script:
  - cd --
  - ls
  - cd /Analisis
  - mkdir build
  - cd helloworld
  - cmake cmake -H. -B../build
  - cd ../build
  - make
  - ./hello
  - ls
  - ls

  
