language: cpp

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgtest-dev
  - sudo apt-get install -y cmake
  - cd /usr/src/gtest
  - ls
compiler:
  - g++

script:
  - cd Analisis
  - mkdir build
  - cd helloworld
  - cmake cmake -H. -B../build
  - cd ../build
  - make
  - ./hello
  - ls
  - ls

  
